"""
Mock AI provider.

A deterministic, offline implementation of `AIProvider`. It produces realistic-
looking results WITHOUT calling any external API, so the whole app can run
locally, in tests, and in CI with zero cost or API keys.

"Deterministic" means: the same inputs always yield the same output. We achieve
this by deriving everything from the input text and the keyword-based skill
extraction (no randomness, no timestamps).
"""

from __future__ import annotations

from app.ai.base import AIProvider, AnalysisResult
from app.services.skills import extract_skills


class MockAIProvider(AIProvider):
    """Deterministic stand-in for a real LLM provider."""

    name = "mock"

    def analyze(
        self, resume_text: str, job_description_text: str
    ) -> AnalysisResult:
        # Reuse the keyword extractor so the mock is grounded in the actual text.
        resume_skills = set(extract_skills(resume_text))
        job_skills = set(extract_skills(job_description_text))

        # Skills the job asks for that appear / don't appear in the resume.
        matched = sorted(job_skills & resume_skills)
        missing = sorted(job_skills - resume_skills)

        score = self._score(matched_count=len(matched), job_count=len(job_skills))
        summary = self._summary(score, matched, missing)
        cover_letter = self._cover_letter(matched, missing)

        return AnalysisResult(
            score=score,
            missing_skills=missing,
            matched_skills=matched,
            summary=summary,
            cover_letter=cover_letter,
            provider=self.name,
        )

    # ----- Deterministic helpers -----

    @staticmethod
    def _score(matched_count: int, job_count: int) -> int:
        """
        Compute a 0–100 score from skill overlap.

        If the job lists no known skills we can't measure overlap, so we return
        a neutral baseline. Otherwise the score is the percentage of required
        skills found in the resume.
        """
        if job_count == 0:
            return 50
        return round(100 * matched_count / job_count)

    @staticmethod
    def _summary(score: int, matched: list[str], missing: list[str]) -> str:
        """Build a short, human-readable explanation of the result."""
        if score >= 80:
            verdict = "strong match"
        elif score >= 50:
            verdict = "partial match"
        else:
            verdict = "weak match"

        matched_str = ", ".join(matched) if matched else "none of the listed skills"
        missing_str = ", ".join(missing) if missing else "no major gaps"

        return (
            f"This resume is a {verdict} for the role (score {score}/100). "
            f"Matched skills: {matched_str}. "
            f"Skills to highlight or develop: {missing_str}. "
            f"[Generated by the mock provider — not a real AI assessment.]"
        )

    @staticmethod
    def _cover_letter(matched: list[str], missing: list[str]) -> str:
        """Produce a templated cover letter referencing the detected skills."""
        strengths = (
            ", ".join(matched)
            if matched
            else "a strong foundation in the role's core areas"
        )
        growth = (
            f" I am also actively strengthening my skills in {', '.join(missing)}."
            if missing
            else ""
        )

        return (
            "Dear Hiring Manager,\n\n"
            "I am excited to apply for this position. My background aligns well "
            f"with your requirements, particularly my experience with {strengths}."
            f"{growth}\n\n"
            "I am confident that my skills and enthusiasm would let me contribute "
            "meaningfully to your team, and I would welcome the opportunity to "
            "discuss how I can help.\n\n"
            "Thank you for your time and consideration.\n\n"
            "Sincerely,\n"
            "Mike Sharifi"
        )
