"use client";

/**
 * Analysis result view (Epic 6).
 *
 * Renders the AI output for a saved comparison:
 *  - the match score (with a colored ring),
 *  - a short summary,
 *  - matched and missing skills,
 *  - the generated cover letter with a copy-to-clipboard button.
 *
 * It is purely presentational; data comes from the `Comparison` returned by the
 * backend after analysis.
 */

import { CopyButton } from "@/components/CopyButton";
import type { Comparison } from "@/lib/types";

export function AnalysisResult({
  result,
  onReset,
  resetLabel = "Analyze another",
}: {
  result: Comparison;
  /** Optional action button (e.g. reset the form). Hidden when omitted. */
  onReset?: () => void;
  resetLabel?: string;
}) {
  const matched = result.extracted_skills?.matched ?? [];
  const missing = result.missing_skills ?? [];
  const score = result.score ?? 0;

  return (
    <div className="space-y-6">
      {/* Header: score + provider */}
      <div className="flex items-center gap-4">
        <ScoreBadge score={score} />
        <div>
          <p className="font-semibold">Match score</p>
          <p className="text-sm text-slate-500">
            Generated by the{" "}
            <span className="font-mono">{result.provider ?? "unknown"}</span>{" "}
            provider · record #{result.id}
          </p>
        </div>
      </div>

      {/* Summary */}
      {result.summary && (
        <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700">
          {result.summary}
        </p>
      )}

      {/* Skills */}
      <div className="grid gap-4 sm:grid-cols-2">
        <SkillList
          title="Matched skills"
          skills={matched}
          tone="green"
          emptyText="No overlapping skills detected."
        />
        <SkillList
          title="Missing skills"
          skills={missing}
          tone="amber"
          emptyText="No major skill gaps found."
        />
      </div>

      {/* Cover letter */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Generated cover letter</h4>
          {result.cover_letter && (
            <CopyButton text={result.cover_letter} label="Copy cover letter" />
          )}
        </div>
        <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-800">
          {result.cover_letter ?? "No cover letter generated."}
        </pre>
      </div>

      {onReset && (
        <button
          type="button"
          onClick={onReset}
          className="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-100"
        >
          {resetLabel}
        </button>
      )}
    </div>
  );
}

/** Circular score badge whose color reflects the match strength. */
function ScoreBadge({ score }: { score: number }) {
  const tone =
    score >= 80
      ? "bg-green-100 text-green-700"
      : score >= 50
        ? "bg-amber-100 text-amber-700"
        : "bg-red-100 text-red-700";

  return (
    <div
      className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-full text-xl font-bold ${tone}`}
    >
      {score}
    </div>
  );
}

/** Labeled list of skills as pills, with an empty state. */
function SkillList({
  title,
  skills,
  tone,
  emptyText,
}: {
  title: string;
  skills: string[];
  tone: "green" | "amber";
  emptyText: string;
}) {
  const pill =
    tone === "green"
      ? "bg-green-100 text-green-800"
      : "bg-amber-100 text-amber-800";

  return (
    <div className="rounded-lg border border-slate-200 p-3">
      <h4 className="mb-2 text-sm font-semibold">{title}</h4>
      {skills.length === 0 ? (
        <p className="text-sm text-slate-400">{emptyText}</p>
      ) : (
        <ul className="flex flex-wrap gap-2">
          {skills.map((skill) => (
            <li
              key={skill}
              className={`rounded-full px-2.5 py-1 text-xs font-medium ${pill}`}
            >
              {skill}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
