import { describe, expect, it } from "vitest";

import {
  applicationPdfFileName,
  extractCompanyName,
  extractJobTitle,
} from "@/lib/extractJobContext";
import {
  APPLICANT_NAME,
  parseLetterSections,
  prepareCoverLetterForPdf,
} from "@/lib/prepareCoverLetterForPdf";

describe("extractJobContext", () => {
  it("reads company from explicit label", () => {
    expect(
      extractCompanyName("Company: Acme Labs\nWe need a Python engineer."),
    ).toBe("Acme Labs");
  });

  it("reads job title from first line suffix", () => {
    expect(
      extractJobTitle("Acme Labs — Senior Python Engineer\nRequirements..."),
    ).toBe("Senior Python Engineer");
  });

  it("builds a professional filename", () => {
    expect(applicationPdfFileName("Acme Labs")).toBe("Mike-Sharifi-Acme-Labs.pdf");
  });
});

describe("prepareCoverLetterForPdf", () => {
  it("replaces placeholder name and strips ai disclosure", () => {
    const raw =
      "Dear Hiring Manager,\n\nBody text.\n\nSincerely,\n[Your Name]\n\n" +
      "(This letter was generated by the mock provider for development purposes.)";

    const prepared = prepareCoverLetterForPdf(raw);

    expect(prepared).toContain(APPLICANT_NAME);
    expect(prepared).not.toContain("[Your Name]");
    expect(prepared.toLowerCase()).not.toContain("mock provider");
  });

  it("parses salutation, body, and closing", () => {
    const sections = parseLetterSections(
      "Dear Hiring Manager,\n\nI am excited to apply.\n\nSincerely,\nMike Sharifi",
    );

    expect(sections.salutation).toBe("Dear Hiring Manager,");
    expect(sections.paragraphs).toEqual(["I am excited to apply."]);
    expect(sections.closing).toBe("Sincerely,");
    expect(sections.signature).toBe(APPLICANT_NAME);
  });
});
