export const APPLICANT_NAME = "Mike Sharifi";

const AI_DISCLOSURE_LINE =
  /\(.*\b(?:mock provider|generated by|ai\b|not a real|development purposes)\b.*\)/i;

export type LetterSections = {
  salutation: string | null;
  paragraphs: string[];
  closing: string | null;
  signature: string;
};

export function prepareCoverLetterForPdf(raw: string): string {
  let text = raw
    .replace(/\[Your Name\]/gi, APPLICANT_NAME)
    .replace(/\[your name\]/gi, APPLICANT_NAME);

  text = text
    .split("\n")
    .filter((line) => !AI_DISCLOSURE_LINE.test(line.trim()))
    .filter((line) => !/\b(?:generated by the mock provider|not a real ai)\b/i.test(line))
    .join("\n")
    .trim();

  if (!new RegExp(APPLICANT_NAME, "i").test(text)) {
    text = text.replace(/(sincerely,?\s*)$/i, `$1\n${APPLICANT_NAME}`);
    if (!new RegExp(APPLICANT_NAME, "i").test(text)) {
      text = `${text}\n\nSincerely,\n${APPLICANT_NAME}`;
    }
  }

  return text.trim();
}

export function parseLetterSections(preparedText: string): LetterSections {
  const blocks = preparedText
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter(Boolean);

  let salutation: string | null = null;
  let closing: string | null = null;
  const paragraphs: string[] = [];
  let signature = APPLICANT_NAME;

  for (const block of blocks) {
    const flat = block.replace(/\n/g, " ").trim();

    if (/^dear\s+/i.test(flat)) {
      salutation = flat;
      continue;
    }

    if (/^sincerely,?\s*$/i.test(flat)) {
      closing = "Sincerely,";
      continue;
    }

    if (new RegExp(`^sincerely,?\\s+${APPLICANT_NAME}$`, "i").test(flat)) {
      closing = "Sincerely,";
      signature = APPLICANT_NAME;
      continue;
    }

    if (new RegExp(`^${APPLICANT_NAME}$`, "i").test(flat)) {
      signature = APPLICANT_NAME;
      continue;
    }

    paragraphs.push(flat);
  }

  return { salutation, paragraphs, closing, signature };
}

/** @deprecated Use APPLICANT_NAME */
export const COVER_LETTER_SIGNATURE = APPLICANT_NAME;
